project:
  type: book

execute:
  freeze: auto
  echo: true

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

comments:
  hypothesis: true

book:
  repo-url: "https://github.com/munch-group/widgetplots"
  repo-actions: [edit, issue, source]  
  title: "Widget plots for Jupyter"
  author: "Kasper Munch"  
  chapters:
    - index.qmd
    - part: "Notebooks"
      chapters: 
      - notebooks/showcase.ipynb
     
bibliography: references.bib
