{% set data = load_setup_py_data() %}

package:
  name: template
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/template.git

build:
  # noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:       # write here the list of libraries to look for your library dependencies
    - python
    # - jupyter
    # - ipython
    # - matplotlib>=3.0
    # - numpy>=1.1
    # - requests
    # - biopython
    # - goatools>=1.2
    # - pytables
    # - wget

channels:    # write here the list of channels to look for your library dependencies
  # - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  - conda-verify
  
test:
  imports:
    - template
  # commands:
  #   - exercises --help    

about:
  home: https://github.com/munch-group/template.git
  license: MIT
  # summary: "Blah blah"
  # description: |
  #   "Blah blah"
  #   "Blah blah"
  dev_url: https://github.com/munch-group/template.git
  doc_url: https://munch-group.org/template
